// This file will be auto-generated by Supabase CLI.
// Run `pnpm supabase:types` (or `npm run supabase:types` / `yarn supabase:types`) to generate it.
// Make sure to replace YOUR_PROJECT_ID_HERE in package.json with your actual Supabase project ID.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// Add a placeholder for the public schema, or leave it to be generated.
// Example:
// export interface Database {
//   public: {
//     Tables: {
//       // your_table_name: {
//       //   Row: {}; // The data expected to be returned from a "select" statement.
//       //   Insert: {}; // The data expected passed to an "insert" statement.
//       //   Update: {}; // The data expected passed to an "update" statement.
//       // };
//     };
//     Views: {
//       // your_view_name: {
//       //   Row: {}; // The data expected to be returned from a "select" statement.
//       // };
//     };
//     Functions: {
//       // your_function_name: {
//       //   Args: {}; // The arguments passed to the function.
//       //   Returns: {}; // The data expected to be returned from the function.
//       // };
//     };
//   };
// }
